-- Migration 023: Seed TDAH Protocol Library (45 protocolos)
-- Gerado automaticamente em 2026-03-13
-- Bible: AXIS_TDAH v2.5

BEGIN;

-- Adicionar colunas que faltam na tabela (criada pela 022 sem elas)
ALTER TABLE tdah_protocol_library ADD COLUMN IF NOT EXISTS bible_version VARCHAR(10);
ALTER TABLE tdah_protocol_library ADD COLUMN IF NOT EXISTS system_fields JSONB;
ALTER TABLE tdah_protocol_library ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- Limpar protocolos existentes antes de inserir (os 14 da 022 serão substituídos por 45 completos)
DELETE FROM tdah_protocol_library;

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A01', 'Iniciar tarefa em até 2 minutos', 'Atenção e permanência em tarefa', 'P1', 'Reduzir a latência entre a instrução de início e o primeiro comportamento funcional alinhado à tarefa. Protocolo de entrada do Bloco A — trata especificamente o custo de ativação inicial.', '2.5', '{"protocol_id": "TDAH-A01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","latency_window_minutes": 2,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A02', 'Permanecer on-task por bloco curto', 'Atenção e permanência em tarefa', 'P1', 'Aumentar o engajamento funcional contínuo em blocos curtos de atividade acadêmica. Trabalha permanência após início — complementa A01 (início) e precede A05 (ampliação de tempo).', '2.5', '{"protocol_id": "TDAH-A02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","block_duration_minutes": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A03', 'Retomar tarefa após distração', 'Atenção e permanência em tarefa', 'P1', 'Aumentar a capacidade de retornar à tarefa após distração/interrupção sem reinício completo ou redirecionamento excessivo. Foca em: reduzir tempo perdido após quebra, fortalecer retomada funcional, evitar que distração breve vire abandono total.', '2.5', '{"protocol_id": "TDAH-A03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","distraction_definition": "","return_window_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A04', 'Completar atividade com divisão em passos', 'Atenção e permanência em tarefa', 'P1', 'Aumentar a probabilidade de conclusão de atividade por meio de divisão explícita em passos menores, sequenciais e mensuráveis. Reduzir sobrecarga diante de tarefas longas, aumentar visibilidade do progresso e fortalecer sustentação executiva.', '2.5', '{"protocol_id": "TDAH-A04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","expected_outcome": "","steps_count": 0,"functional_hypothesis": "","planned_antecedent": "","defined_reinforcement": "","main_context": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A05', 'Aumentar tempo de permanência progressiva', 'Atenção e permanência em tarefa', 'P1', 'Ampliar gradualmente a duração funcional de permanência em tarefa sem saltos bruscos de exigência. Expande blocos toleráveis com progressão realista, não força de resistência.', '2.5', '{"protocol_id": "TDAH-A05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","base_duration_minutes": 0,"target_duration_minutes": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-A06', 'Reduzir evasão de demanda leve', 'Atenção e permanência em tarefa', 'P1', 'Reduzir microcomportamentos de fuga/evasão que comprometem início, manutenção ou conclusão de demandas funcionais — mesmo sem explosão comportamental. Transforma esquiva sutil em variável observável e tratável.', '2.5', '{"protocol_id": "TDAH-A06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","evasion_definition": "","max_evasion_per_block": 1,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B01', 'Seguir instrução de 1 passo', 'Seguimento de instruções e rotina', 'P1', 'Estabelecer ou fortalecer o seguimento de instrução de passo único — base de toda a cadeia do Bloco B. Reduzir latência, repetição excessiva e dependência de escalada verbal.', '2.5', '{"protocol_id": "TDAH-B01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","instruction_type": "","latency_window_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B02', 'Seguir instrução de 2 passos', 'Seguimento de instruções e rotina', 'P1', 'Ampliar resposta funcional de instrução unitária para cadeia curta de 2 passos. Reduzir perda do segundo elemento, diminuir repetição excessiva do adulto e fortalecer memória funcional imediata.', '2.5', '{"protocol_id": "TDAH-B02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_instruction": "","order_required": true,"time_window_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B03', 'Completar rotina matinal com apoio visual', 'Seguimento de instruções e rotina', 'P1', 'Estruturar a rotina matinal como sequência funcional com apoio visual, reduzindo dependência de lembretes verbais, conflitos e atrasos recorrentes na preparação para sair.', '2.5', '{"protocol_id": "TDAH-B03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","morning_routine_steps": [],"visual_support_type": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B04', 'Completar rotina de saída', 'Seguimento de instruções e rotina', 'P1', 'Organizar e estabilizar a etapa final da rotina de saída: reduzir atrasos, esquecimentos, dependência de múltiplos comandos e quebra da sequência entre estar em casa e efetivamente partir para o compromisso.', '2.5', '{"protocol_id": "TDAH-B04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","departure_steps": [],"essential_items": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B05', 'Completar rotina de dever', 'Seguimento de instruções e rotina', 'P1', 'Estruturar o dever de casa como rotina funcional previsível com começo, meio e fim claros. Reduzir postergação, conflito, evasão e abandono da tarefa acadêmica.', '2.5', '{"protocol_id": "TDAH-B05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","homework_routine_steps": [],"completion_criterion": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-B06', 'Transitar entre atividades com menor resistência', 'Seguimento de instruções e rotina', 'P1', 'Reduzir resistência e desorganização na passagem entre atividades. Aumentar capacidade de encerrar ação atual e iniciar a seguinte com menor custo comportamental, menor atraso e menor intervenção do adulto.', '2.5', '{"protocol_id": "TDAH-B06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","origin_activity": "","destination_activity": "","transition_time_criterion_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C01', 'Reduzir interrupções verbais', 'Impulsividade e autocontrole', 'P1', 'Reduzir frequência de interrupções verbais impulsivas em contextos estruturados — sala de aula, atividade em grupo, refeição. Diferenciar impulsividade verbal de problemas pragmáticos ou ansiedade social.', '2.5', '{"protocol_id": "TDAH-C01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","max_interruptions_per_block": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C02', 'Esperar a vez em contexto estruturado', 'Impulsividade e autocontrole', 'P1', 'Ensinar a aguardar a vez em atividades estruturadas com regra de turno clara — jogo, roda, fila, atividade em grupo — sem invasão de turno, sem protesto intenso e com comportamento compatível durante a espera.', '2.5', '{"protocol_id": "TDAH-C02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_activity": "","wait_time_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C03', 'Pedir ajuda de forma adequada', 'Impulsividade e autocontrole', 'P1', 'Ensinar a substituir fuga, protesto, travamento silencioso ou interrupção inadequada por um pedido funcional, claro e socialmente adequado de ajuda. Criar alternativa funcional quando a criança não consegue avançar sozinha.', '2.5', '{"protocol_id": "TDAH-C03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","help_request_form": "","target_context": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C04', 'Reduzir levantar do lugar sem permissão', 'Impulsividade e autocontrole', 'P1', 'Reduzir saídas motoras impulsivas e não funcionais do lugar em contextos estruturados. Aumentar permanência física compatível com a atividade, diferenciando necessidade real de movimento de quebra desorganizada do contexto.', '2.5', '{"protocol_id": "TDAH-C04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_context": "","max_exits_per_block": 1,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C05', 'Tolerar pequena espera com reforço planejado', 'Impulsividade e autocontrole', 'P1', 'Aumentar a capacidade de tolerar pequenas esperas em contextos funcionais, mantendo comportamento compatível até o acesso ao reforço, item, turno ou atividade previamente combinados. Treinar atraso pequeno, previsível e ligado a contingência clara.', '2.5', '{"protocol_id": "TDAH-C05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_reinforcer": "","initial_wait_seconds": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-C06', 'Pausar antes de responder', 'Impulsividade e autocontrole', 'P1', 'Ensinar a inserir uma pausa funcional entre o estímulo e a resposta em situações de alta probabilidade de reação impulsiva. Reduzir respostas automáticas precipitadas e aumentar autorregulação pré-resposta.', '2.5', '{"protocol_id": "TDAH-C06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_context": "","pause_form": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D01', 'Organizar mochila/material', 'Organização e planejamento', 'P1', 'Construir rotina funcional e autônoma de organização da mochila e materiais escolares, reduzindo esquecimentos, dependência de supervisão adulta intensa e conflitos recorrentes ligados à preparação de material.', '2.5', '{"protocol_id": "TDAH-D01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","material_list": [],"fixed_time": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D02', 'Usar checklist de tarefa', 'Organização e planejamento', 'P1', 'Ensinar o uso funcional e autônomo de checklist como andaime executivo. Reduzir dependência de instrução verbal do adulto e aumentar a capacidade de guiar execução de tarefa pela estrutura visual do checklist.', '2.5', '{"protocol_id": "TDAH-D02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","checklist_items": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D03', 'Iniciar pelo primeiro passo sem procrastinação extensa', 'Organização e planejamento', 'P1', 'Reduzir o tempo entre a instrução de início e o primeiro comportamento funcional alinhado à tarefa. Trabalhar especificamente o déficit de ativação — o custo de "entrar" na tarefa — não a continuidade em si.', '2.5', '{"protocol_id": "TDAH-D03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_task": "","first_step_definition": "","latency_window_minutes": 2,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D04', 'Finalizar tarefa antes de trocar de atividade', 'Organização e planejamento', 'P1', 'Treinar o fechamento funcional de tarefa antes de transitar para outra atividade. Combate a tendência de abandonar no meio ou trocar de atividade impulsivamente sem conclusão, criando padrão de "fechar antes de abrir".', '2.5', '{"protocol_id": "TDAH-D04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","closure_definition": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D05', 'Revisar material antes de encerrar', 'Organização e planejamento', 'P1', 'Treinar revisão funcional do próprio trabalho antes de encerrar, como habilidade executiva de monitoramento. Reduzir erros por descuido, trabalhos incompletos entregues e ausência de checagem pré-encerramento.', '2.5', '{"protocol_id": "TDAH-D05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","review_checklist": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-D06', 'Usar timer visual para blocos de trabalho', 'Organização e planejamento', 'P1', 'Ensinar o uso funcional de timer visual como andaime externo de percepção de tempo. Reduzir dependência de lembretes verbais do adulto e aumentar autorregulação temporal durante blocos de trabalho.', '2.5', '{"protocol_id": "TDAH-D06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","timer_type": "","block_duration_minutes": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E01', 'Implementar sistema de reforço doméstico', 'Regulação emocional e comportamental', 'P1', 'Estruturar sistema de reforço doméstico funcional, consistente e calibrado ao perfil da criança. Substituir dinâmicas de coerção/punição por contingências positivas claras que aumentem adesão e cooperação no cotidiano.', '2.5', '{"protocol_id": "TDAH-E01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","system_format": "","target_behaviors": [],"identified_reinforcers": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E02', 'Elogio específico e contingente', 'Regulação emocional e comportamental', 'P1', 'Treinar responsáveis e profissionais a usar elogio específico, contingente e funcional como reforçador social eficaz. Substituir elogios genéricos, atrasados ou desconectados do comportamento por resposta imediata e descritiva que fortaleça o comportamento-alvo.', '2.5', '{"protocol_id": "TDAH-E02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_behaviors": [],"praise_format": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E03', 'Instrução objetiva e consistente', 'Regulação emocional e comportamental', 'P1', 'Treinar responsáveis e educadores a emitir instruções curtas, objetivas, afirmativas e consistentes. Reduzir sobrecarga verbal, comandos longos, repetições em cascata e negociações que comprometem o seguimento de instrução da criança com TDAH.', '2.5', '{"protocol_id": "TDAH-E03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_contexts": [],"instruction_format_trained": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E04', 'Resposta planejada a não seguimento de regra', 'Regulação emocional e comportamental', 'P1', 'Treinar responsáveis a responder ao não seguimento de regra de forma planejada, calma e consistente — sem escalada emocional, sem ceder sob pressão e sem punição desproporcional. Substituir reatividade por protocolo.', '2.5', '{"protocol_id": "TDAH-E04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","non_compliance_situations": [],"planned_response": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E05', 'Reduzir escalada coercitiva em rotina doméstica', 'Regulação emocional e comportamental', 'P1', 'Identificar e interromper ciclos coercitivos estabelecidos no cotidiano doméstico — onde protesto/não seguimento e cedência/escalada do adulto se retroalimentam. Reconstruir contingência funcional no lugar do ciclo de coerção.', '2.5', '{"protocol_id": "TDAH-E05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","coercive_cycles_mapped": [],"entry_point": "","planned_adult_response": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-E06', 'Implantar economia de fichas em casa', 'Regulação emocional e comportamental', 'P1', 'Implementar sistema de economia de fichas no ambiente doméstico como andaime motivacional visual, concreto e previsível. Complementa E01 com estrutura mais formalizada para crianças que respondem melhor a reforço concreto e sistemático.', '2.5', '{"protocol_id": "TDAH-E06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","token_type": "","exchange_criterion": 0,"target_behaviors": [],"reinforcers": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F01', 'DRC de permanência em tarefa', 'Habilidades sociais e comunicação', 'P1', 'DRC focado em permanência on-task em sala de aula. Objetiva a queixa mais frequente na escola ("não fica na tarefa") em dado registrável e comunicável diariamente.', '2.5', '{"protocol_id": "TDAH-F01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","on_task_criterion": "","home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F02', 'DRC de conclusão de atividade', 'Habilidades sociais e comunicação', 'P1', 'Implementar DRC focado em conclusão funcional de atividades escolares, criando canal de comunicação escola-família baseado em comportamento observável, não em impressão geral. Integrar dado escolar ao planejamento clínico.', '2.5', '{"protocol_id": "TDAH-F02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","drc_target": "","daily_criterion": "","home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F03', 'DRC de redução de interrupções', 'Habilidades sociais e comunicação', 'P1', 'DRC focado em frequência de interrupções em sala de aula. Criar registro objetivo e comunicação escola-família para uma das queixas mais frequentes: criança interrompe professor, colegas ou atividade de forma excessiva.', '2.5', '{"protocol_id": "TDAH-F03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","interruption_definition": "","max_per_block": 0,"home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F04', 'DRC de seguir instruções do professor', 'Habilidades sociais e comunicação', 'P1', 'DRC focado em seguimento de instruções do professor em sala de aula. Objetivar a queixa "não obedece" em dado registrável e comunicável, criando loop escola-família-clínica funcional.', '2.5', '{"protocol_id": "TDAH-F04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","instruction_criterion": "","home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F05', 'DRC de organização escolar', 'Habilidades sociais e comunicação', 'P1', 'DRC focado em organização de material e rotina escolar. Cria dado objetivo sobre cadernos, material, mesa e itens escolares para monitoramento família-escola com intervenção clínica articulada.', '2.5', '{"protocol_id": "TDAH-F05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","organization_criterion": "","home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-F06', 'Plano escola-casa com reforço cruzado', 'Habilidades sociais e comunicação', 'P1', 'Coordenar contingências entre escola e casa para comportamentos-alvo que dependem de continuidade entre contextos. Vai além do DRC simples — cria plano integrado com reforço cruzado (escola registra → casa reforça → clínica monitora).', '2.5', '{"protocol_id": "TDAH-F06","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","school_target": "","home_reinforcer": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G01', 'Reconhecer sinal inicial de desregulação', 'Suporte regulatório e AuDHD', 'P1', 'Ensinar a identificar sinais corporais e comportamentais precoces de desregulação emocional — antes da explosão ou ruptura. Criar janela de intervenção antes que o ciclo escape ao controle. Pré-condição para G02 e toda a sequência de regulação.', '2.5', '{"protocol_id": "TDAH-G01","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","personal_signals_map": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G02', 'Solicitar pausa de forma funcional', 'Suporte regulatório e AuDHD', 'P1', 'Ensinar a comunicar necessidade de pausa regulatória antes de atingir ponto de ruptura, usando forma previamente combinada, funcional e compreensível para os adultos do contexto. Criar alternativa funcional à explosão ou fuga desorganizada.', '2.5', '{"protocol_id": "TDAH-G02","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","pause_signal_form": "","adults_trained": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G03', 'Usar recurso visual para retorno à tarefa', 'Suporte regulatório e AuDHD', 'P1', 'Ensinar o uso de recurso visual (cartão, checklist, marcador) como andaime concreto para retornar à tarefa após pausa ou distração. Reduzir dependência de instrução verbal do adulto para reorientação.', '2.5', '{"protocol_id": "TDAH-G03","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","visual_resource_type": "","target_task": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G04', 'Tolerar mudança pequena com previsibilidade', 'Suporte regulatório e AuDHD', 'P1', 'Aumentar a tolerância a pequenas variações esperadas na rotina ou tarefa, por meio de antecipação, previsibilidade e exposição gradual calibrada. Reduzir reação excessiva a mudanças mínimas que perturbam o funcionamento cotidiano.', '2.5', '{"protocol_id": "TDAH-G04","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","target_variation": "","advance_notice_minutes": 0,"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G05', 'Modular demanda com reforço diferencial', 'Suporte regulatório e AuDHD', 'P1', 'Ajustar nível e formato da demanda de forma sistemática, combinado com reforço diferencial, para reduzir custo comportamental do engajamento e aumentar cooperação funcional. Usa calibração de demanda como variável clínica — não como cedência.', '2.5', '{"protocol_id": "TDAH-G05","version": "2.5","audhd_layer_status": "off | active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","demand_modulation": "","differential_reinforcement": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G06', 'Plano combinado para sensorialidade + tarefa', 'Suporte regulatório e AuDHD', 'P1', 'Criar plano integrado que combina suporte sensorial com estrutura de tarefa para crianças com perfil AuDHD nas quais a permanência, o início ou a conclusão da tarefa são fortemente impactados por sobrecarga sensorial, necessidade de regulação prévia ou alta vulnerabilidade a estímulos concorrentes.', '2.5', '{"protocol_id": "TDAH-G06","version": "2.5","audhd_layer_status": "active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","sensory_support": [],"task_structure": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G08', 'Reduzir atrito em transição entre demandas', 'Suporte regulatório e AuDHD', 'P1.1', 'Reduzir o custo comportamental e regulatório de transições entre demandas diferentes, com atenção especial ao perfil AuDHD onde a rigidez executiva e o custo de mudança de estado são fatores centrais — não apenas impulsividade ou "birra".', '2.5', '{"protocol_id": "TDAH-G08","version": "2.5","audhd_layer_status": "active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","demand_origin": "","demand_destination": "","anticipation_resource": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G10', 'Ajustar rotina sob sobrecarga sensorial previsível', 'Suporte regulatório e AuDHD', 'P1.1', 'Ensinar a antecipar e ajustar funcionamento em dias/períodos com sobrecarga sensorial previsível — antes que o acúmulo leve à desregulação. Intervenção proativa, não apenas reativa.', '2.5', '{"protocol_id": "TDAH-G10","version": "2.5","audhd_layer_status": "active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","sensory_contexts_mapped": [],"planned_adjustments": [],"functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G11', 'Manejo de custo adaptativo invisível', 'Suporte regulatório e AuDHD', 'P1.1', 'Reconhecer e manejar o custo regulatório oculto do mascaramento adaptativo (camouflage/masking) — esforço invisível de adequação social que drena recursos regulatórios e precipita desregulação tardia. Protocolo central no perfil AuDHD.', '2.5', '{"protocol_id": "TDAH-G11","version": "2.5","audhd_layer_status": "active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","collapse_pattern": "","decompression_strategy": "","post_context_demand_reduction": "","functional_hypothesis": ""}'::jsonb, true);

INSERT INTO tdah_protocol_library (code, title, block, priority, description, bible_version, system_fields, is_active)
VALUES ('TDAH-G12', 'Regulação pós-esforço adaptativo', 'Suporte regulatório e AuDHD', 'P1.1', 'Estruturar estratégias e rotinas de recuperação regulatória após períodos de esforço adaptativo intenso. Fecha a sequência G10 → G11 → G12: sobrecarga previsível → custo acumulado → regulação pós-esforço.', '2.5', '{"protocol_id": "TDAH-G12","version": "2.5","audhd_layer_status": "active_core | active_full","snapshot_type": "initial | progress | closure","source_record_id": "","restorative_activities": [],"recovery_window_minutes": 0,"demanding_contexts": [],"functional_hypothesis": ""}'::jsonb, true);

COMMIT;

-- Verificar resultado
-- SELECT code, title, block, priority FROM tdah_protocol_library ORDER BY code;