-- =====================================================
-- Migration 043: INTENCIONALMENTE NEUTRALIZADA (no-op)
--
-- HISTÓRIA
-- ---------
-- Escrita em 2026-03-24 para "corrigir" portal_get_summaries()
-- (criada na migration 014), assumindo que session_summaries
-- tinha colunas summary_text/is_approved.
--
-- Em 2026-04-17 (validação funcional VPS produção) foi confirmado:
-- o schema real de session_summaries sempre teve content + status
-- (VARCHAR). A migration 007 define summary_text/is_approved, mas
-- NUNCA foi aplicada nesta tabela.
--
-- A versão da função em prod vem da migration 014:
--   ss.content + ss.status = 'approved'  ← correto (bate com DB real)
--
-- Esta migration 043 está deliberadamente vazia (no-op) para:
--   1. Preservar numeração sequencial
--   2. Impedir que a versão incorreta (ss.summary_text AS content,
--      sent_at IS NOT NULL) seja aplicada e sobrescreva a 014
--   3. Documentar o episódio do schema mismatch 17/04
--
-- NÃO REESCREVER. Ver docs/NOTE_ABA.md → Fase 2 schema sweep.
-- =====================================================

-- (intentionally no SQL — this is a no-op migration)
